platform_aws_account_number             = "728675847142"
hosted_zone                             = "seed.mfe.dev.platform.q4inc.com"
rolename_suffix                          = " [$(UPPERCASE_ENVIRONMENT)]"
domain_stage                            = "$(ENVIRONMENT)."
subdomain                               = "$(ENVIRONMENT)."
platform_hosted_zone                    = "dev.platform.q4inc.com"
terraform_remote_state_bucket           = "state.terraform.dev.connect.q4inc.com.us-east-1"
terraform_remote_state_connect_base_key = "environment/dev/com/q4inc/connect/"
